import type { DSColors } from "./DesignSystemContext";

/* ─── Preset palettes ─── */
// TODO: Add the user's custom color palette as the FIRST entry in this array.
// This makes it the default color palette (DEFAULT_DS_COLORS references DS_PRESETS[0]).
export const DS_PRESETS: { name: string; colors: DSColors }[] = [
  {
    name: "Terracotta & Gold",
    colors: {
      primary: "#BF5836",
      onPrimary: "#FFFFFF",
      primaryContainer: "#FFDBC8",
      onPrimaryContainer: "#983E1E",
      secondary: "#8D5E3C",
      onSecondary: "#FFFFFF",
      secondaryContainer: "#FADDCA",
      onSecondaryContainer: "#5C3A1E",
      tertiary: "#C59B26",
      onTertiary: "#3B2900",
      tertiaryContainer: "#FFEDB0",
      onTertiaryContainer: "#82660D",
      success: "#1B873B",
      onSuccess: "#FFFFFF",
      successContainer: "#D4F5DC",
      onSuccessContainer: "#0D5E26",
      error: "#BA1A1A",
      onError: "#FFFFFF",
      errorContainer: "#FFDAD6",
      onErrorContainer: "#8C1D18",
      surface: "#FFFFFF",
      onSurface: "#1C1B1B",
      surfaceVariant: "#E8E0DE",
      onSurfaceVariant: "#4D4544",
      surfaceContainerHighest: "#E0E0E0",
      surfaceContainerHigh: "#EAEAEA",
      surfaceContainer: "#F2F2F2",
      surfaceContainerLow: "#F7F7F7",
      surfaceContainerLowest: "#FFFFFF",
      inverseSurface: "#313030",
      inverseOnSurface: "#F4F0EF",
      surfaceTint: "#BF5836",
      surfaceTintColor: "#BF5836",
      outline: "#7D7574",
      outlineVariant: "#D0C8C6",
    },
  },
  {
    name: "Ocean Breeze",
    colors: {
      primary: "#0D47A1",
      onPrimary: "#FFFFFF",
      primaryContainer: "#D1E4FF",
      onPrimaryContainer: "#0A3577",
      secondary: "#2E7D72",
      onSecondary: "#FFFFFF",
      secondaryContainer: "#C8F5F0",
      onSecondaryContainer: "#1A5C53",
      tertiary: "#C62828",
      onTertiary: "#FFFFFF",
      tertiaryContainer: "#FFDAD6",
      onTertiaryContainer: "#8E0000",
      success: "#2E7D32",
      onSuccess: "#FFFFFF",
      successContainer: "#C8E6C9",
      onSuccessContainer: "#1B5E20",
      error: "#C62828",
      onError: "#FFFFFF",
      errorContainer: "#FFCDD2",
      onErrorContainer: "#8E0000",
      surface: "#FFFFFF",
      onSurface: "#1A1C1E",
      surfaceVariant: "#DEE3EB",
      onSurfaceVariant: "#42474E",
      surfaceContainerHighest: "#D8E0EA",
      surfaceContainerHigh: "#E2E8F0",
      surfaceContainer: "#EBF0F7",
      surfaceContainerLow: "#F2F6FC",
      surfaceContainerLowest: "#FFFFFF",
      inverseSurface: "#2E3133",
      inverseOnSurface: "#F0F1F4",
      surfaceTint: "#0D47A1",
      surfaceTintColor: "#0D47A1",
      outline: "#72787E",
      outlineVariant: "#C2C7CE",
    },
  },
  {
    name: "Midnight Violet",
    colors: {
      primary: "#6957A0",
      onPrimary: "#FFFFFF",
      primaryContainer: "#F0E8FF",
      onPrimaryContainer: "#3D2E6B",
      secondary: "#37474F",
      onSecondary: "#FFFFFF",
      secondaryContainer: "#CFE0E8",
      onSecondaryContainer: "#1E3038",
      tertiary: "#BF4000",
      onTertiary: "#FFFFFF",
      tertiaryContainer: "#FFE0B2",
      onTertiaryContainer: "#8C3100",
      success: "#2E7D32",
      onSuccess: "#FFFFFF",
      successContainer: "#C8E6C9",
      onSuccessContainer: "#1B5E20",
      error: "#B71C1C",
      onError: "#FFFFFF",
      errorContainer: "#FFDAD6",
      onErrorContainer: "#8C1D18",
      surface: "#FFFFFF",
      onSurface: "#1C1B1F",
      surfaceVariant: "#E7E0EC",
      onSurfaceVariant: "#49454F",
      surfaceContainerHighest: "#E4DFE9",
      surfaceContainerHigh: "#EAE5EF",
      surfaceContainer: "#F0ECF5",
      surfaceContainerLow: "#F7F2FA",
      surfaceContainerLowest: "#FFFFFF",
      inverseSurface: "#312F35",
      inverseOnSurface: "#F4EFF7",
      surfaceTint: "#6957A0",
      surfaceTintColor: "#6957A0",
      outline: "#7A757F",
      outlineVariant: "#CBC4D0",
    },
  },
  {
    name: "Emerald Garden",
    colors: {
      primary: "#1B5E20",
      onPrimary: "#FFFFFF",
      primaryContainer: "#C8E6C9",
      onPrimaryContainer: "#0D3B12",
      secondary: "#3E2723",
      onSecondary: "#FFFFFF",
      secondaryContainer: "#E6D3CC",
      onSecondaryContainer: "#2A1A17",
      tertiary: "#BF4000",
      onTertiary: "#FFFFFF",
      tertiaryContainer: "#FFF0C2",
      onTertiaryContainer: "#7C3700",
      success: "#2E7D32",
      onSuccess: "#FFFFFF",
      successContainer: "#C8E6C9",
      onSuccessContainer: "#1B5E20",
      error: "#C62828",
      onError: "#FFFFFF",
      errorContainer: "#FFCDD2",
      onErrorContainer: "#8E0000",
      surface: "#FFFFFF",
      onSurface: "#1A1C1A",
      surfaceVariant: "#DEE5DB",
      onSurfaceVariant: "#424940",
      surfaceContainerHighest: "#D8E2D6",
      surfaceContainerHigh: "#E2EBE0",
      surfaceContainer: "#ECF3EA",
      surfaceContainerLow: "#F3F9F2",
      surfaceContainerLowest: "#FFFFFF",
      inverseSurface: "#2E322D",
      inverseOnSurface: "#EFF2EB",
      surfaceTint: "#1B5E20",
      surfaceTintColor: "#1B5E20",
      outline: "#72796F",
      outlineVariant: "#C2C9BD",
    },
  },
  {
    name: "Arctic Frost",
    colors: {
      primary: "#263238",
      onPrimary: "#FFFFFF",
      primaryContainer: "#CFD8DC",
      onPrimaryContainer: "#1A2328",
      secondary: "#37474F",
      onSecondary: "#FFFFFF",
      secondaryContainer: "#D4E4EB",
      onSecondaryContainer: "#1E3038",
      tertiary: "#005662",
      onTertiary: "#FFFFFF",
      tertiaryContainer: "#B2EBF2",
      onTertiaryContainer: "#003640",
      success: "#2E7D32",
      onSuccess: "#FFFFFF",
      successContainer: "#C8E6C9",
      onSuccessContainer: "#1B5E20",
      error: "#C62828",
      onError: "#FFFFFF",
      errorContainer: "#FFCDD2",
      onErrorContainer: "#8E0000",
      surface: "#FFFFFF",
      onSurface: "#1A1C1D",
      surfaceVariant: "#DFE3E5",
      onSurfaceVariant: "#43474A",
      surfaceContainerHighest: "#D9DFE2",
      surfaceContainerHigh: "#E3E8EA",
      surfaceContainer: "#ECEFF1",
      surfaceContainerLow: "#F4F6F7",
      surfaceContainerLowest: "#FFFFFF",
      inverseSurface: "#2E3132",
      inverseOnSurface: "#F0F2F3",
      surfaceTint: "#263238",
      surfaceTintColor: "#263238",
      outline: "#73777A",
      outlineVariant: "#C3C7CA",
    },
  },
  {
    name: "Berry Dusk",
    colors: {
      primary: "#880E4F",
      onPrimary: "#FFFFFF",
      primaryContainer: "#FFD9E3",
      onPrimaryContainer: "#5C0935",
      secondary: "#2C2C2C",
      onSecondary: "#FFFFFF",
      secondaryContainer: "#E0E0E0",
      onSecondaryContainer: "#1A1A1A",
      tertiary: "#BF360C",
      onTertiary: "#FFFFFF",
      tertiaryContainer: "#FFDBC8",
      onTertiaryContainer: "#8C2600",
      success: "#2E7D32",
      onSuccess: "#FFFFFF",
      successContainer: "#C8E6C9",
      onSuccessContainer: "#1B5E20",
      error: "#B71C1C",
      onError: "#FFFFFF",
      errorContainer: "#FFDAD6",
      onErrorContainer: "#8C1D18",
      surface: "#FFFFFF",
      onSurface: "#201A1B",
      surfaceVariant: "#F2DDE1",
      onSurfaceVariant: "#514347",
      surfaceContainerHighest: "#ECDFE2",
      surfaceContainerHigh: "#F2E5E8",
      surfaceContainer: "#F8EBEE",
      surfaceContainerLow: "#FEF1F3",
      surfaceContainerLowest: "#FFFFFF",
      inverseSurface: "#362F30",
      inverseOnSurface: "#FAEDEF",
      surfaceTint: "#880E4F",
      surfaceTintColor: "#880E4F",
      outline: "#817076",
      outlineVariant: "#D5C2C6",
    },
  },
  {
    name: "Slate & Citrus",
    colors: {
      primary: "#1A252F",
      onPrimary: "#FFFFFF",
      primaryContainer: "#C8D6E0",
      onPrimaryContainer: "#0F1820",
      secondary: "#3D5A1E",
      onSecondary: "#FFFFFF",
      secondaryContainer: "#E4F0B8",
      onSecondaryContainer: "#263B0F",
      tertiary: "#7C5800",
      onTertiary: "#FFFFFF",
      tertiaryContainer: "#FFF0B3",
      onTertiaryContainer: "#5A3F00",
      success: "#2E7D32",
      onSuccess: "#FFFFFF",
      successContainer: "#C8E6C9",
      onSuccessContainer: "#1B5E20",
      error: "#C62828",
      onError: "#FFFFFF",
      errorContainer: "#FFCDD2",
      onErrorContainer: "#8E0000",
      surface: "#FFFFFF",
      onSurface: "#1A1C1E",
      surfaceVariant: "#E0E2E5",
      onSurfaceVariant: "#44474B",
      surfaceContainerHighest: "#DADDE0",
      surfaceContainerHigh: "#E4E6E9",
      surfaceContainer: "#EDEEF0",
      surfaceContainerLow: "#F4F5F7",
      surfaceContainerLowest: "#FFFFFF",
      inverseSurface: "#2F3133",
      inverseOnSurface: "#F0F1F3",
      surfaceTint: "#1A252F",
      surfaceTintColor: "#1A252F",
      outline: "#74777B",
      outlineVariant: "#C4C7CB",
    },
  },
];

/* ─── Default palette (references first preset) ─── */
export const DEFAULT_DS_COLORS: DSColors = DS_PRESETS[0].colors;
